package com.andreaplloci.thesisobdapp.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // ConnectionScreen
    val connectTitle: String,
    val connectSubtitle: String,
    val connectButton: String,
    val connecting: String,
    val selectDevice: String,
    val noDevices: String,
    val integrityInterface: String,
    val integrityProtocol: String,
    val integritySecurity: String,
    val ready: String,
    val search: String,
    val obdNotResponding: String,

    // SelectionScreen
    val vehicleDataTitle: String,
    val savedProfiles: String,
    val loadProfile: String,
    val profileLoaded: String,
    val reportLanguage: String,
    val brand: String,
    val model: String,
    val year: String,
    val engine: String,
    val gearbox: String,
    val currentKm: String,
    val startScan: String,

    // ReadingScreen
    val preparingProtocol: String,
    val noDeviceSelected: String,
    val connectionFailed: String,
    val reading: String,
    val attempt: String,
    val scanningDtc: String,
    val back: String,
    val labelEct: String,
    val labelLoad: String,
    val labelMaf: String,
    val labelBattery: String,
    val labelIat: String,
    val labelRail: String,

    // DiagnosticScreen
    val missingData: String,
    val finalDataTitle: String,
    val infoCallout: String,
    val emailLabel: String,
    val serviceHistory: String,
    val km: String,
    val description: String,
    val addWork: String,
    val generateReport: String,
    val sendFailed: String,

    // SuccessScreen
    val reportSent: String,
    val analysisComplete: (String) -> String,
    val backToDashboard: String
)

val StringsIT = AppStrings(
    connectTitle = "JARVIS HUB",
    connectSubtitle = "Connetti l'interfaccia OBD-II per iniziare",
    connectButton = "CERCA E CONNETTI OBD",
    connecting = "CONNESSIONE...",
    selectDevice = "SELEZIONA DISPOSITIVO",
    noDevices = "Nessun dispositivo abbinato. Abbina il tuo OBD nelle impostazioni Bluetooth.",
    integrityInterface = "Interfaccia",
    integrityProtocol = "Protocollo",
    integritySecurity = "Sicurezza",
    ready = "PRONTO",
    search = "RICERCA",
    obdNotResponding = "OBD non risponde. Verifica che il dispositivo sia acceso e in range.",
    vehicleDataTitle = "DATI VEICOLO",
    savedProfiles = "PROFILI SALVATI",
    loadProfile = "Carica profilo",
    profileLoaded = "Profilo caricato — inserisci i km attuali e avvia.",
    reportLanguage = "Lingua Report",
    brand = "Marca",
    model = "Modello",
    year = "Anno",
    engine = "Motorizzazione",
    gearbox = "Tipo di Cambio",
    currentKm = "KM Attuali",
    startScan = "AVVIA SCANSIONE",
    preparingProtocol = "Preparazione Protocollo...",
    noDeviceSelected = "Nessun dispositivo selezionato. Torna alla connessione.",
    connectionFailed = "Connessione fallita. Verifica il dispositivo OBD e riprova.",
    reading = "Lettura",
    attempt = "Tentativo",
    scanningDtc = "Scansione DTC...",
    back = "Torna Indietro",
    labelEct = "ECT",
    labelLoad = "Carico Motore",
    labelMaf = "MAF",
    labelBattery = "Batteria",
    labelIat = "Temp. Aspirazione",
    labelRail = "Pressione Rail",
    missingData = "Errore: dati mancanti. Torna indietro e riprova.",
    finalDataTitle = "DATI FINALI JARVIS",
    infoCallout = "Compila l'email e aggiungi eventuali interventi eseguiti sul veicolo.",
    emailLabel = "La tua Email",
    serviceHistory = "STORICO INTERVENTI",
    km = "KM",
    description = "Descrizione",
    addWork = "Aggiungi Lavoro",
    generateReport = "GENERA REPORT",
    sendFailed = "Invio fallito. Controlla la connessione e riprova.",
    reportSent = "REPORT INVIATO!",
    analysisComplete = { marca -> "Analisi Jarvis completata per $marca." },
    backToDashboard = "TORNA ALLA DASHBOARD"
)

val StringsEN = AppStrings(
    connectTitle = "JARVIS HUB",
    connectSubtitle = "Connect the OBD-II interface to get started",
    connectButton = "SCAN & CONNECT OBD",
    connecting = "CONNECTING...",
    selectDevice = "SELECT DEVICE",
    noDevices = "No paired devices found. Pair your OBD adapter in Bluetooth settings.",
    integrityInterface = "Interface",
    integrityProtocol = "Protocol",
    integritySecurity = "Security",
    ready = "READY",
    search = "SEARCH",
    obdNotResponding = "OBD not responding. Make sure the device is on and in range.",
    vehicleDataTitle = "VEHICLE DATA",
    savedProfiles = "SAVED PROFILES",
    loadProfile = "Load profile",
    profileLoaded = "Profile loaded — enter current mileage and start.",
    reportLanguage = "Report Language",
    brand = "Brand",
    model = "Model",
    year = "Year",
    engine = "Engine",
    gearbox = "Gearbox",
    currentKm = "Current KM",
    startScan = "START SCAN",
    preparingProtocol = "Preparing Protocol...",
    noDeviceSelected = "No device selected. Go back to connection.",
    connectionFailed = "Connection failed. Check your OBD device and try again.",
    reading = "Reading",
    attempt = "Attempt",
    scanningDtc = "Scanning DTCs...",
    back = "Go Back",
    labelEct = "ECT",
    labelLoad = "Engine Load",
    labelMaf = "MAF",
    labelBattery = "Battery",
    labelIat = "Intake Temp",
    labelRail = "Rail Pressure",
    missingData = "Error: missing data. Go back and try again.",
    finalDataTitle = "FINAL JARVIS DATA",
    infoCallout = "Fill in your email and add any maintenance work done on the vehicle.",
    emailLabel = "Your Email",
    serviceHistory = "SERVICE HISTORY",
    km = "KM",
    description = "Description",
    addWork = "Add Work",
    generateReport = "GENERATE REPORT",
    sendFailed = "Send failed. Check your connection and try again.",
    reportSent = "REPORT SENT!",
    analysisComplete = { marca -> "Jarvis analysis completed for $marca." },
    backToDashboard = "BACK TO DASHBOARD"
)

val StringsDE = AppStrings(
    connectTitle = "JARVIS HUB",
    connectSubtitle = "OBD-II-Schnittstelle verbinden, um zu beginnen",
    connectButton = "OBD SUCHEN & VERBINDEN",
    connecting = "VERBINDEN...",
    selectDevice = "GERÄT AUSWÄHLEN",
    noDevices = "Keine gekoppelten Geräte. Koppeln Sie den OBD-Adapter in den Bluetooth-Einstellungen.",
    integrityInterface = "Schnittstelle",
    integrityProtocol = "Protokoll",
    integritySecurity = "Sicherheit",
    ready = "BEREIT",
    search = "SUCHE",
    obdNotResponding = "OBD antwortet nicht. Stellen Sie sicher, dass das Gerät eingeschaltet und in Reichweite ist.",
    vehicleDataTitle = "FAHRZEUGDATEN",
    savedProfiles = "GESPEICHERTE PROFILE",
    loadProfile = "Profil laden",
    profileLoaded = "Profil geladen — aktuelle KM eingeben und starten.",
    reportLanguage = "Berichtssprache",
    brand = "Marke",
    model = "Modell",
    year = "Jahr",
    engine = "Motor",
    gearbox = "Getriebe",
    currentKm = "Aktueller KM-Stand",
    startScan = "SCAN STARTEN",
    preparingProtocol = "Protokoll wird vorbereitet...",
    noDeviceSelected = "Kein Gerät ausgewählt. Zurück zur Verbindung.",
    connectionFailed = "Verbindung fehlgeschlagen. OBD-Gerät prüfen und erneut versuchen.",
    reading = "Lese",
    attempt = "Versuch",
    scanningDtc = "DTC-Scan läuft...",
    back = "Zurück",
    labelEct = "ECT",
    labelLoad = "Motorlast",
    labelMaf = "MAF",
    labelBattery = "Batterie",
    labelIat = "Ansaugtemp.",
    labelRail = "Rail-Druck",
    missingData = "Fehler: fehlende Daten. Zurück und erneut versuchen.",
    finalDataTitle = "JARVIS ABSCHLUSSDATEN",
    infoCallout = "E-Mail ausfüllen und eventuelle Wartungsarbeiten am Fahrzeug hinzufügen.",
    emailLabel = "Ihre E-Mail",
    serviceHistory = "WARTUNGSHISTORIE",
    km = "KM",
    description = "Beschreibung",
    addWork = "Arbeit hinzufügen",
    generateReport = "BERICHT ERSTELLEN",
    sendFailed = "Senden fehlgeschlagen. Verbindung prüfen und erneut versuchen.",
    reportSent = "BERICHT GESENDET!",
    analysisComplete = { marca -> "Jarvis-Analyse abgeschlossen für $marca." },
    backToDashboard = "ZURÜCK ZUM DASHBOARD"
)

fun stringsForLanguage(lingua: String): AppStrings = when (lingua) {
    "English" -> StringsEN
    "Deutsch" -> StringsDE
    else -> StringsIT
}

val LocalAppStrings = compositionLocalOf<AppStrings> { StringsIT }
